### ISSUE TITLE
newline makes last character that same size

### ISSUE THREAD

**Issue by jmonroynieto** [joethei/obsidian-control-characters#14]
When modifying the size of the characters with CSS, the newline changes the line it is in. See image.

```css
.control-character[type=newline],[type=space],[type=tab] {
	font-size: small;
}
```

![Screenshot 2023-06-20 at 3 53 56 AM](https://github.com/joethei/obsidian-control-characters/assets/10119293/4e52962d-07e9-4f07-b1de-a8dff8bf284b)

It also breaks the rendering of emojis. An extra space at the end avoids this, but it is not ideal.
